name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  myjob:
    runs-on: ubuntu-latest
    env:
      callingjobinput1: "This is my first input"
      callingjobinput2: "This is my second input" 
    steps:
      - uses: actions/checkout@v2

      - name: Hello world calling workflow
        run: echo "Hello from calling workflow" 

      - uses: jonjozwiak/actions-workflows/.github/workflows/sample-passing-inputs-and-secrets.yml@main
        with:
          input1: $callingjobinput1
          input2: $callingjobinput2
        secrets:
          mysecret1: ${{ secrets.calling_workflow_secret1 }}
          mysecret2: ${{ secrets.calling_workflow_secret2 }}
