name: Call a reusable workflow

on:
  workflow_dispatch:

env:
  callingjobinput1: "This is my first input"
  callingjobinput2: "This is my second input" 

jobs:
  myjob1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hello world calling workflow
        run: echo "Hello from calling workflow" 
  myjob2:
    uses: jonjozwiak/actions-workflows/.github/workflows/sample-passing-inputs-and-secrets.yml@main
    with:
      input1: ${{ env.callingjobinput1 }}
      input2: ${{ env.callingjobinput2 }}
    secrets:
      mysecret1: ${{ secrets.calling_workflow_secret1 }}
      mysecret2: ${{ secrets.calling_workflow_secret2 }}
